---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: myns
spec:
  type: LoadBalancer
  externalIPs:
   - 44.204.237.100
  ports:
  - name: http
    port: 3000
    targetPort: 8080
  selector:
    name: app-image
